### ISSUE TITLE
Far distance

### ISSUE THREAD

**Issue by brightsider** [gleue/TGLAugmentedRealityView#1]
Hello. Can you help to improve working with far distances?

**Comment by gleue** [comment]
The projection matrix is computed in `TGLARView -updateProjectionMatrix` -- see `TGLARView.m:805`.

Here you'll find a call to `GLKMatrix4MakePerspective` with near and far values as parameters 3 and 4.

**Comment by gleue** [comment]
Or did you have something else in mind?

**Comment by brightsider** [comment]
@gleue thanks. Maybe it's worth to make variable for TGLARView?

**Comment by gleue** [comment]
I added optional TGLARViewDelegate methods -- see 1.0.2
